---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/konflux-qe-bd/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-main-tyrx
